### ISSUE TITLE
internal/util/inspect.js:31 const types = internalBinding('types');

### ISSUE THREAD

**Issue by lkimsey** [ivanmrchk/gulp-and-browsersync#1]
[lk@blackbird gulp-and-browsersync]$ gulp
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/lab/FRAMEWORKS/utils/gulp-and-browsersync/node_modules/natives/index.js:137:5)
    at require (/lab/FRAMEWORKS/utils/gulp-and-browsersync/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/lab/FRAMEWORKS/utils/gulp-and-browsersync/node_modules/natives/index.js:137:5)
    at require (/lab/FRAMEWORKS/utils/gulp-and-browsersync/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/lab/FRAMEWORKS/utils/gulp-and-browsersync/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/lab/FRAMEWORKS/utils/gulp-and-browsersync/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/lab/FRAMEWORKS/utils/gulp-and-browsersync/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
[lk@blackbird gulp-and-browsersync]$ gulp --v
CLI version: 2.2.0
Local version: 3.9.1

**Comment by ivanmrchk** [comment]
What node js version are you using, try the stable one 10.x

**Comment by lkimsey** [comment]
followed https://stackoverflow.com/questions/54433794/gulp-internalbinding-is-not-defined.  problem fixed.
